version: '2'
services:
  ocr-service_rabbitmq:
    image: rabbitmq:3-management
    container_name: ocr-service_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME_ENV}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD_ENV}
